name: Build and deploy Full-Stack Node.js App to Azure Web App - TrafficlightPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js 18.x for backend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Build backend
        working-directory: server
        run: npm run build

      - name: Setup Node.js 18.x for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: server/dist # Assuming backend is built into 'dist' folder

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: client/build # Assuming frontend is built into 'build' folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ secrets.AZURE_WEBAPP_URL }} # Adjust with your actual Azure Web App URL

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend

      - name: Deploy to Azure Web App - Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          slot-name: 'Production'
          package: backend
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # Adjust with your actual Azure Publish Profile secret

      - name: Deploy to Azure Web App - Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          slot-name: 'Production'
          package: frontend
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # Adjust with your actual Azure Publish Profile secret
