name: Build and deploy Node.js app to Azure Web App - TrafficlightPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Backend (Server) Build
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Backend Dependencies
        run: npm install
        working-directory: server   # Change directory to server where backend package.json is located
      - name: Build Backend
        run: npm run build --if-present
        working-directory: server   # Make sure to run build commands in the server directory
      
      # Frontend (Client) Build
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install
      - name: Build Frontend
        run: |
          cd client
          npm run build --if-present

      # Upload Backend artifact for deployment job
      - name: Upload Backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: server   # Upload backend artifacts from the server directory
          if-no-files-found: error

      # Upload Frontend artifact for deployment job
      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: client/build
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download Backend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Download Frontend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: frontend
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          package: .
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
