name: Build and deploy Node.js app to Azure Web App - TrafficlightPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Backend (Server) Build
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '14.x' # Choose the appropriate version
      - name: Install Backend Dependencies
        run: npm install
      - name: Build Backend
        run: npm run build --if-present
      - name: Test Backend
        run: npm run test --if-present

      # Frontend (Client) Build
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '14.x' # Choose the appropriate version
      - name: Install Frontend Dependencies
        run: |
          cd client # Assuming frontend code is in a 'client' directory
          npm install
      - name: Build Frontend
        run: |
          cd client # Assuming frontend code is in a 'client' directory
          npm run build --if-present

      # Upload Backend artifact for deployment job
      - name: Upload Backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: .

      # Upload Frontend artifact for deployment job
      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: client/build # Assuming frontend build output is in 'client/build' directory

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ secrets.AZURE_WEB_APP_URL }}
    
    steps:
      - name: Download Backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend
      
      - name: Download Frontend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          package: .
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
