# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TrafficlightPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install npm dependencies for frontend (client)
      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      # Install npm dependencies for backend (server)
      - name: Install backend dependencies
        working-directory: server
        run: npm install

      # Build frontend (client)
      - name: Build frontend
        working-directory: client
        run: npm run build

      # Build backend (server)
      - name: Build backend
        working-directory: server
        run: npm run build

      # Upload frontend artifact for deployment job
      - name: Upload frontend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: client-app
          path: client/build

      # Upload backend artifact for deployment job
      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: server-app
          path: server/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: client-app

      - name: Download backend artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: server-app
      
      - name: 'Deploy frontend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          slot-name: 'Production'
          package: ${{ github.workspace }}/client-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C5DF583BD304445A806D75FE776D7163 }}

      - name: 'Deploy backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TrafficlightPro'
          slot-name: 'Production'
          package: ${{ github.workspace }}/server-app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C5DF583BD304445A806D75FE776D7163 }}
